"""
Aubo i3H-specific data loader for Motion Policy Networks training.

Directory structure expected:
    data_dir/
      train/
        *.hdf5
        *_cache.hdf5   (optional, generated by scripts/precompute_point_cloud_cache.py)
      val/
        *.hdf5
        *_cache.hdf5   (optional)
"""
from pathlib import Path
from typing import Optional, Dict
import os

import h5py
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl
from pyquaternion import Quaternion
from geometrout.primitive import Cuboid, Cylinder

from robofin.samplers_aubo import TorchAuboSampler
from robofin.robots_aubo import AuboRobot
from robofin.robot_constants_aubo import AuboConstants

from mpinets.geometry import construct_mixed_point_cloud
from mpinets.utils_aubo import normalize_aubo_joints

import enum


class DatasetType(enum.Enum):
    TRAIN = 0
    VAL = 1
    TEST = 2


class AuboPointCloudBase(Dataset):
    """
    Base dataset class for Aubo i3H.  Handles filesystem discovery and the
    core point-cloud construction logic.  Subclasses provide __len__ /
    __getitem__ tailored for training vs. validation.
    """

    def __init__(
        self,
        directory: Path,
        trajectory_key: str,
        num_robot_points: int,
        num_obstacle_points: int,
        num_target_points: int,
        dataset_type: DatasetType,
        random_scale: float,
    ):
        self._init_directory(directory, dataset_type)
        self.trajectory_key = trajectory_key
        self.train = dataset_type == DatasetType.TRAIN
        with h5py.File(str(self._database), "r") as f:
            self._num_trajectories = f[self.trajectory_key].shape[0]
            self.expert_length = f[self.trajectory_key].shape[1]

        self.num_obstacle_points = num_obstacle_points
        self.num_robot_points = num_robot_points
        self.num_target_points = num_target_points
        self.random_scale = random_scale
        # Sampler is created on-demand to avoid spawning threads in worker 0
        self._fk_sampler: Optional[TorchAuboSampler] = None
        self._h5_file: Optional[h5py.File] = None
        # Cache file (precomputed target/obstacle point clouds)
        self._cache_h5_file: Optional[h5py.File] = None
        self._cache_path: Optional[Path] = self._discover_cache()

    def _init_directory(self, directory: Path, dataset_type: DatasetType):
        self.type = dataset_type
        if dataset_type == DatasetType.TRAIN:
            directory = directory / "train"
        elif dataset_type == DatasetType.VAL:
            directory = directory / "val"
        elif dataset_type == DatasetType.TEST:
            directory = directory / "test"
        else:
            raise ValueError(f"Invalid dataset type: {dataset_type}")
        databases = list(directory.glob("**/*.hdf5"))
        # Filter out cache files so only the primary HDF5 is matched
        databases = [p for p in databases if not p.stem.endswith("_cache")]
        assert len(databases) == 1, f"Expected 1 hdf5 in {directory}, got {databases}"
        self._database = databases[0]

    def _discover_cache(self) -> Optional[Path]:
        """Look for a companion *_cache.hdf5 with compatible parameters."""
        candidate = self._database.parent / (self._database.stem + "_cache.hdf5")
        if not candidate.exists():
            return None
        try:
            with h5py.File(str(candidate), "r") as cf:
                if (
                    cf.attrs.get("num_obstacle_points") == self.num_obstacle_points
                    and cf.attrs.get("num_target_points") == self.num_target_points
                    and cf.attrs.get("trajectory_key") == self.trajectory_key
                ):
                    print(f"[AuboDataset] Using precomputed cache: {candidate}")
                    return candidate
                else:
                    print(
                        f"[AuboDataset] Cache {candidate} has incompatible params "
                        f"(obstacle={cf.attrs.get('num_obstacle_points')}, "
                        f"target={cf.attrs.get('num_target_points')}, "
                        f"key={cf.attrs.get('trajectory_key')}), ignoring."
                    )
                    return None
        except Exception as exc:
            print(f"[AuboDataset] Could not open cache {candidate}: {exc}")
            return None

    @property
    def _sampler(self) -> TorchAuboSampler:
        if self._fk_sampler is None:
            self._fk_sampler = TorchAuboSampler(
                num_robot_points=max(self.num_robot_points, self.num_target_points),
                use_cache=True,
                device="cpu",
            )
        return self._fk_sampler

    @property
    def num_trajectories(self):
        return self._num_trajectories

    @property
    def h5_file(self) -> h5py.File:
        """Open one read-only HDF5 handle per DataLoader worker."""
        if self._h5_file is None:
            self._h5_file = h5py.File(str(self._database), "r")
        return self._h5_file

    @property
    def cache_file(self) -> Optional[h5py.File]:
        """Open one read-only cache handle per DataLoader worker."""
        if self._cache_path is None:
            return None
        if self._cache_h5_file is None:
            self._cache_h5_file = h5py.File(str(self._cache_path), "r")
        return self._cache_h5_file

    def __getstate__(self):
        state = self.__dict__.copy()
        # HDF5 file handles cannot be pickled; re-open lazily in each worker
        state["_h5_file"] = None
        state["_fk_sampler"] = None
        state["_cache_h5_file"] = None
        return state

    def __del__(self):
        for attr in ("_h5_file", "_cache_h5_file"):
            f = getattr(self, attr, None)
            if f is not None:
                try:
                    f.close()
                except Exception:
                    pass

    @staticmethod
    def normalize(config_tensor: torch.Tensor) -> torch.Tensor:
        result = normalize_aubo_joints(config_tensor)
        assert isinstance(result, torch.Tensor)
        return result

    def get_inputs(self, trajectory_idx: int, timestep: int) -> Dict[str, torch.Tensor]:
        item: Dict[str, torch.Tensor] = {}
        f = self.h5_file

        # Read full trajectory slice once (tiny: T*6*4 bytes) to avoid
        # multiple separate HDF5 round-trips for target/current/supervision.
        traj = f[self.trajectory_key][trajectory_idx]  # (T, DOF)
        config_tensor = torch.as_tensor(traj[timestep], dtype=torch.float32)

        # Supervision config (training only) — next timestep, clamped to last
        if self.train:
            supervision_t = min(timestep + 1, self.expert_length - 1)
            item["supervision"] = self.normalize(
                torch.as_tensor(traj[supervision_t], dtype=torch.float32)
            )

        # Current robot config with optional random perturbation (training only)
        joint_limits = torch.as_tensor(AuboConstants.JOINT_LIMITS, dtype=torch.float32)
        if self.train:
            randomized = self.random_scale * torch.randn_like(config_tensor) + config_tensor
            randomized = torch.clamp(randomized, joint_limits[:, 0], joint_limits[:, 1])
            item["configuration"] = self.normalize(randomized)
            robot_q = randomized
        else:
            item["configuration"] = self.normalize(config_tensor)
            robot_q = config_tensor

        # Robot point cloud — must be computed at runtime (depends on perturbed config)
        robot_points = self._sampler.sample(
            robot_q.unsqueeze(0), num_points=self.num_robot_points
        )[0, :, :3]  # (N_robot, 3)

        # --- Target and obstacle point clouds ---
        # Use precomputed cache when available; otherwise compute on the fly.
        cache = self.cache_file
        if cache is not None:
            item["target_position"] = torch.as_tensor(
                cache["target_position"][trajectory_idx], dtype=torch.float32
            )
            target_points = torch.as_tensor(
                cache["target_points"][trajectory_idx], dtype=torch.float32
            )  # (N_target, 3)
            obstacle_points_np = np.asarray(cache["obstacle_points"][trajectory_idx])
        else:
            target_q = torch.as_tensor(traj[-1], dtype=torch.float32)
            target_pose = AuboRobot.fk(target_q.numpy())
            target_pose_mat = torch.as_tensor(target_pose.matrix, dtype=torch.float32)
            target_points = self._sampler.sample_end_effector(
                target_pose_mat, num_points=self.num_target_points
            )[0, :, :3]  # (N_target, 3)
            item["target_position"] = torch.as_tensor(target_pose.xyz, dtype=torch.float32)
            obstacle_points_np = None  # computed below after reading geometry

        # --- Obstacle geometry (always needed for loss computation) ---
        cuboid_dims = f["cuboid_dims"][trajectory_idx, ...]
        if cuboid_dims.ndim == 1:
            cuboid_dims = np.expand_dims(cuboid_dims, 0)
        cuboid_centers = f["cuboid_centers"][trajectory_idx, ...]
        if cuboid_centers.ndim == 1:
            cuboid_centers = np.expand_dims(cuboid_centers, 0)
        cuboid_quats = f["cuboid_quaternions"][trajectory_idx, ...]
        if cuboid_quats.ndim == 1:
            cuboid_quats = np.expand_dims(cuboid_quats, 0)
        cuboid_quats[np.all(np.isclose(cuboid_quats, 0), axis=1), 0] = 1.0

        item["cuboid_dims"] = torch.as_tensor(cuboid_dims)
        item["cuboid_centers"] = torch.as_tensor(cuboid_centers)
        item["cuboid_quats"] = torch.as_tensor(cuboid_quats)

        if "cylinder_radii" not in f.keys():
            cylinder_radii = np.array([[0.0]])
            cylinder_heights = np.array([[0.0]])
            cylinder_centers = np.array([[0.0, 0.0, 0.0]])
            cylinder_quats = np.array([[1.0, 0.0, 0.0, 0.0]])
        else:
            cylinder_radii = f["cylinder_radii"][trajectory_idx, ...]
            if cylinder_radii.ndim == 1:
                cylinder_radii = np.expand_dims(cylinder_radii, 0)
            cylinder_heights = f["cylinder_heights"][trajectory_idx, ...]
            if cylinder_heights.ndim == 1:
                cylinder_heights = np.expand_dims(cylinder_heights, 0)
            cylinder_centers = f["cylinder_centers"][trajectory_idx, ...]
            if cylinder_centers.ndim == 1:
                cylinder_centers = np.expand_dims(cylinder_centers, 0)
            cylinder_quats = f["cylinder_quaternions"][trajectory_idx, ...]
            if cylinder_quats.ndim == 1:
                cylinder_quats = np.expand_dims(cylinder_quats, 0)
            cylinder_quats[np.all(np.isclose(cylinder_quats, 0), axis=1), 0] = 1.0

        item["cylinder_radii"] = torch.as_tensor(cylinder_radii)
        item["cylinder_heights"] = torch.as_tensor(cylinder_heights)
        item["cylinder_centers"] = torch.as_tensor(cylinder_centers)
        item["cylinder_quats"] = torch.as_tensor(cylinder_quats)

        # Compute obstacle point cloud if not loaded from cache
        if obstacle_points_np is None:
            cuboids = [
                Cuboid(c, d, q)
                for c, d, q in zip(
                    list(cuboid_centers), list(cuboid_dims), list(cuboid_quats)
                )
            ]
            cuboids = [c for c in cuboids if not c.is_zero_volume()]
            cylinders = [
                Cylinder(c, r, h, q)
                for c, r, h, q in zip(
                    list(cylinder_centers),
                    list(cylinder_radii.squeeze(1)),
                    list(cylinder_heights.squeeze(1)),
                    list(cylinder_quats),
                )
            ]
            cylinders = [c for c in cylinders if not c.is_zero_volume()]
            obstacle_points_np = construct_mixed_point_cloud(
                cuboids + cylinders, self.num_obstacle_points
            )

        # xyz layout: [robot | obstacles | target]
        item["xyz"] = torch.cat(
            (
                torch.zeros(self.num_robot_points, 4),
                torch.ones(self.num_obstacle_points, 4),
                2 * torch.ones(self.num_target_points, 4),
            ),
            dim=0,
        )
        item["xyz"][: self.num_robot_points, :3] = robot_points.float()
        item["xyz"][
            self.num_robot_points : self.num_robot_points + self.num_obstacle_points, :3
        ] = torch.as_tensor(obstacle_points_np[:, :3], dtype=torch.float32)
        item["xyz"][
            self.num_robot_points + self.num_obstacle_points :, :3
        ] = target_points.float()

        return item


class AuboPointCloudTrajectoryDataset(AuboPointCloudBase):
    """Validation / test dataset: one item per trajectory (start config)."""

    def __init__(self, directory, trajectory_key, num_robot_points,
                 num_obstacle_points, num_target_points, dataset_type):
        assert dataset_type != DatasetType.TRAIN
        super().__init__(
            directory, trajectory_key, num_robot_points,
            num_obstacle_points, num_target_points, dataset_type, random_scale=0.0,
        )

    def __len__(self):
        return self.num_trajectories

    def __getitem__(self, idx: int):
        return self.get_inputs(idx, 0)


class AuboPointCloudInstanceDataset(AuboPointCloudBase):
    """Training dataset: one item per (trajectory, timestep) pair."""

    def __init__(self, directory, trajectory_key, num_robot_points,
                 num_obstacle_points, num_target_points, dataset_type, random_scale):
        super().__init__(
            directory, trajectory_key, num_robot_points,
            num_obstacle_points, num_target_points, dataset_type, random_scale,
        )

    def __len__(self):
        return self.num_trajectories * self.expert_length

    def __getitem__(self, idx: int):
        trajectory_idx, timestep = divmod(idx, self.expert_length)
        if timestep >= self.expert_length:
            timestep = self.expert_length - 1
        # supervision is included in the returned dict by get_inputs (self.train=True)
        return self.get_inputs(trajectory_idx, timestep)


class AuboDataModule(pl.LightningDataModule):
    """PyTorch Lightning DataModule for Aubo i3H training."""

    def __init__(
        self,
        data_dir: str,
        trajectory_key: str,
        num_robot_points: int,
        num_obstacle_points: int,
        num_target_points: int,
        random_scale: float,
        batch_size: int,
        num_workers: Optional[int] = None,
        persistent_workers: bool = True,
        prefetch_factor: int = 2,
    ):
        super().__init__()
        self.data_dir = Path(data_dir)
        self.trajectory_key = trajectory_key
        self.batch_size = batch_size
        self.num_robot_points = num_robot_points
        self.num_obstacle_points = num_obstacle_points
        self.num_target_points = num_target_points
        self.num_workers = (
            min(os.cpu_count() or 1, 30) if num_workers is None else num_workers
        )
        self.persistent_workers = persistent_workers
        self.prefetch_factor = prefetch_factor
        self.random_scale = random_scale

    def setup(self, stage: Optional[str] = None):
        common = dict(
            directory=self.data_dir,
            trajectory_key=self.trajectory_key,
            num_robot_points=self.num_robot_points,
            num_obstacle_points=self.num_obstacle_points,
            num_target_points=self.num_target_points,
        )
        if stage in ("fit", None):
            self.data_train = AuboPointCloudInstanceDataset(
                **common, dataset_type=DatasetType.TRAIN, random_scale=self.random_scale
            )
            self.data_val = AuboPointCloudTrajectoryDataset(
                **common, dataset_type=DatasetType.VAL
            )
            # Pre-warm the FK sampler cache in the main process so all DataLoader
            # workers find the .npy cache file already on disk. Without this,
            # every worker races to write the same file simultaneously, causing SIGBUS.
            _ = self.data_train._sampler
        if stage in ("test", None):
            self.data_test = AuboPointCloudInstanceDataset(
                **common, dataset_type=DatasetType.TEST, random_scale=self.random_scale
            )

    def train_dataloader(self) -> DataLoader:
        kwargs = self._dataloader_kwargs()
        return DataLoader(
            self.data_train,
            self.batch_size,
            **kwargs,
        )

    def val_dataloader(self) -> DataLoader:
        kwargs = self._dataloader_kwargs()
        return DataLoader(
            self.data_val,
            self.batch_size,
            **kwargs,
        )

    def test_dataloader(self) -> DataLoader:
        kwargs = self._dataloader_kwargs()
        return DataLoader(
            self.data_test,
            self.batch_size,
            **kwargs,
        )

    def _dataloader_kwargs(self) -> Dict[str, object]:
        kwargs: Dict[str, object] = {
            "num_workers": self.num_workers,
            "pin_memory": True,
        }
        if self.num_workers > 0:
            kwargs["persistent_workers"] = self.persistent_workers
            kwargs["prefetch_factor"] = self.prefetch_factor
        return kwargs
